CREATE VIEW FIRST
AS
    SELECT S.NAME, S.WORK_NUMBER, P.SUPPLIER_WORK_NUMBER, P.PRODUCT_NAME
    FROM SUPPLIERS S, PRODUCTS P
    WHERE S.WORK_NUMBER = P.SUPPLIER_WORK_NUMBER;

SELECT * FROM FIRST;

CREATE VIEW SECOND
AS
    SELECT G.ATTRACTION_NAME, G.VISITORS_UNIQUE_NUMBER,V.UNIQUE_NUMBER, V.NAME
    FROM GETS_ON G, VISITORS V
    WHERE G.VISITORS_UNIQUE_NUMBER = V.UNIQUE_NUMBER;

SELECT * FROM SECOND;
